config/routes.rb
SiliconCanal::Application.routes.draw do

  post "events/:id/approve" => "events#approve", :as => "approve_event"
  post "events/:id/unapprove" => "events#unapprove", :as => "unapprove_event"

  resources :event_categories
  resources :events

  devise_for :users

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  get "search" => "search#index"
  resources :people
  resources :companies

  root :to => "companies#index"
end

app/views/layouts/application.html.haml
!!!
%html
    %head
        %title Silicon Canal
        = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
        = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css"
        = javascript_include_tag "application", "data-turbolinks-track" => true
        = csrf_meta_tags

    %body

        .container
            .row
                .col-4
                    %h1 Silicon Canal
                .col-4
                    =link_to "Companies", companies_path
                    =link_to "People", people_path
                    =link_to "Events", events_path
                    =link_to "Event Categories", event_categories_path
                    =link_to "Sign Out", destroy_user_session_path, method: :delete
                .col-4
                    =form_tag search_path, method: :get do
                        =text_field_tag(:criteria)
                        =submit_tag("Search")

            %p.notice= notice
            %p.alert= alert
            
            =yield